--- 
# Default agent implementation
:default: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- SaboteurAgent
- SaboteurAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent

# Default implementation without saboteurs
:peace: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- SentinelAgent
- SentinelAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent