--- 
:default: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- SaboteurAgent
- SaboteurAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent
:peace: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- SentinelAgent
- SentinelAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent