--- 
# Default agent implementation
:default: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- SaboteurAgent
- SaboteurAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent

# Default implementation without saboteurs
:peace: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- SentinelAgent
- SentinelAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent

# Default implementation with aggressive saboteurs
:aggressive: 
- ExplorerAgent
- ExplorerAgent
- RepairerAgent
- RepairerAgent
- AggressiveSaboteurAgent
- AggressiveSaboteurAgent
- SentinelAgent
- SentinelAgent
- InspectorAgent
- InspectorAgent